services:
  # Go Backend
  backend:
    build:
      context: ./golang-backend
      dockerfile: Dockerfile
    container_name: neural-decks-backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
      - REDIS_URL=redis://redis:6379
      - DATABASE_DSN=postgresql://postgres:password@neural-decks-postgres-dev:5432/neural_decks
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=neural_decks
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - neural-decks-network

  # React Frontend
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    container_name: neural-decks-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - neural-decks-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: neural-decks-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=neural_decks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - neural-decks-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: neural-decks-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - neural-decks-network

  # Optional: Redis Commander for web-based Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: neural-decks-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - neural-decks-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  neural-decks-network:
    driver: bridge 